version: '2'

services:

  influxdb:
    image: influxdb:1.5.3
    environment:
      INFLUXDB_HTTP_ENABLED: "true"
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
    volumes:
      - ./.data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:5.1.0
    environment:
      GF_LOG_MODE: "file"
      GF_PATHS_LOGS: "/logs"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_DASHBOARDS_JSON_ENABLED: "true"
      GF_DASHBOARDS_JSON_PATH: "/dashboards"
      GF_PATHS_DATA: "/data"
    volumes:
      - ./.data/grafana/dashboards:/dashboards
      - ./.data/grafana/db:/data
      - ./.data/grafana/logs:/logs
    ports:
      - "3000:3000"
